PREFIX  dbpediaowl:  <http://dbpedia.org/ontology/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX yago: <https://dbpedia.org/class/yago/>

SELECT distinct ?city ?state WHERE {
    ?state dbpediaowl:country dbpedia:United_States .
    ?state dbp:isoCode ?isoCode .
    ?city dbpediaowl:subdivision ?state .
    ?city rdf:type dbpediaowl:City .
}