PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX  dbpediaowl:  <http://dbpedia.org/ontology/>
SELECT DISTINCT ?city ?state 
WHERE {
    ?city rdf:type dbo:PopulatedPlace .
     ?city rdfs:label ?label .
   ?city dbo:country dbpedia:United_States .
    ?city dbpediaowl:subdivision ?state .
    ?state dbpediaowl:country dbpedia:United_States .
    ?state dbp:isoCode ?isoCode .
FILTER ( regex(?label, "St Louis"))
     }