SELECT DISTINCT 
        ?restaurantLabel
        ?cityLabel
        ?stateLabel
    WHERE {
        ?restaurant rdf:type tef:restaurant .
        ?restaurant tef:hasMenuItem ?item .
        ?item rdfs:label ?itemLabel .
        ?restaurant rdfs:label ?restaurantLabel .
        ?restaurant tef:restaurantInCity ?city .
        ?city rdfs:label ?cityLabel .
        ?city tef:cityLocatedIn ?state .
        ?state rdfs:label ?stateLabel .
        FILTER ( regex(lcase(str(?itemLabel)), "bianca") || regex(lcase(str(?itemLabel)), "white"))
    }
    GROUP BY ?restaurant
        ?restaurantLabel
        ?cityLabel
        ?stateLabel