name: runDocumentation
# based on https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - run: pip install -r requirements.txt
      - run: cd .. && pdoc --docformat=numpy --favicon https://link477.com/favicon.ico --logo=https://link477.com/assets/images/link477.png -o Pizza_KG/docs/ Pizza_KG
      
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

# deploy to github pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
